version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: evt_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: evt2538
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
